### PR TITLE
GMT DCS

### PR DESCRIPTION
**Pull request by rconan**
Merging the DCS client  presented to SWC into the main branch

### CODE REVIEW

**Comment by rodrigo-romano** [comment]
I am getting errors when tried to build the main binary of the `dcs` client using
`cargo build` from the `dos-actors/clients/dcs` folder.
I set the environmental variables `MOUNT_MODEL` and `FEM_REPO`. The issue is related to `tai_time::MonotonicTime` structure in line 46 of `dos-actors/clients/dcs/src/mount_trajectory.rs`.

Screen Shot 2024-08-29 at 9 08 14 AM

**Comment by rconan** [comment]
Are you testing on a Mac?

**Comment by rconan** [comment]
I may have fix it but I cannot test it on Mac OSes myself

**Comment by rodrigo-romano** [comment]
The inline condition based on `cfg!` was not working. I could solve it using conditional compilation with `#[cfg(..)]` for the full read function as follows
```
impl<U: UniqueIdentifier<DataType = Vec<f64>>> Read<U> for MountTrajectory {
    #[cfg(not(target_os = "macos"))]
    fn read(&mut self, data: interface::Data<U>) {
        self.azimuth.push_back(data[0]);
        self.elevation.push_back(data[1]);
        self.gir.push_back(data[2]);
        let now = MonotonicTime::now();
        self.tai.push_back(Duration::from_nanos(
            now.as_secs() as u64 * 1_000_000_000 + now.subsec_nanos() as u64,
        ));
    }
    #[cfg(target_os = "macos")]
    fn read(&mut self, data: interface::Data<U>) {
        self.azimuth.push_back(data[0]);
        self.elevation.push_back(data[1]);
        self.gir.push_back(data[2]);
        let clock: TaiClock<0> = TaiClock::init_from_utc(0);
        let now = clock.now();
        self.tai.push_back(Duration::from_nanos(
            now.as_secs() as u64 * 1_000_000_000 + now.subsec_nanos() as u64,
        ));
    }
}
```

**Comment by rconan** [comment]
I've implemented your suggestion

**Review by rodrigo-romano — APPROVED** [review]

**Pull request merged**
