### PR TITLE
Unit and doc tests

### PR DESCRIPTION
**Pull request by rconan**
Both `cargo test --lib` and `cargo test --doc` are passing

### CODE REVIEW

**Comment by rconan** [comment]
To check the pull request you have to run
`cargo test --lib --all-features`
and 
`cargo test --doc --all-features`
from dos-actors

I'm using the following setting:
`export FEM_REPO=~/mnt/20230131_1605_zen_30_M1_202110_ASM_202208_Mount_202111/`
and
`export MOUNT_MODEL=MOUNT_FDR_1kHz`

**Review by rodrigo-romano — APPROVED** [review]
I ran `cargo test --lib --all-features` and `cargo test --doc --all-features` from `dos-actors/actors`. I confirm that the tests passed.

`cargo test --lib --all-features`
Screen Shot 2024-07-12 at 9 02 51 AM


`cargo test --doc --all-features`
Screen Shot 2024-07-12 at 9 03 35 AM

**Comment by rconan** [comment]
@rodrigo-romano , could you re-run the tests not from `dos-actors/actors` but from` dos-actors`, testing the whole workspace ?

**Comment by rodrigo-romano** [comment]
Done! Everything is fine.

**Pull request merged**
