### PR TITLE
Changes to save mount data in async_mountloading example

### PR DESCRIPTION
**Pull request by rodrigo-romano**
The following changes implement GIR tooth contact axial force disturbance and modify the `async_mountloading.rs` example to log some extra data: GIR, MNT Enc, and DG(PortB) node positions.

The Python notebook `clients/windloads/examples/mountloading/mnt_wl_withGIR.ipynb` displays the data from the mountloading.rs example.

Remark: The update in `clients/windloads/examples/mnt-m1-wl/main.rs` was accidental; however, it does not affect any functionality or analysis script.

### CODE REVIEW

**Review by rconan — APPROVED** [review]
did you test run async_mountloading?

**Comment by rodrigo-romano** [comment]
Not yet. In line (224) of `main.rs`, can I use 

>for cfd_case in cfd::Baseline::<2021>::default().into_iter().skip(25).take(1)
>{...}

to test a single case?

**Comment by rconan** [comment]
yes exactly

**Comment by rodrigo-romano** [comment]
I ran the async_mountloading example, and the data is saved as expected.

**Pull request merged**
